name: OpenFPM_CI

on:
  pull_request:
  push:
    branches:
      - master
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: apt install -y openssh-clients cmake wget git gcc-c++ gcc-gfortran python39 bzip2 diffutils zlib-devel
      - name: Clone repository
        run: |
          git clone ${{ secrets.GIT_REPOSITORY }} ${{ github.workspace }}
          cd ${{ github.workspace }}
          git checkout ${{ github.ref }}
      - name: make dependencies folder
        run: mkdir -p openfpm_dependencies
      - name: Build
        run: ./build.sh $(pwd) unused pdata 0 ${{ github.ref }}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: openfpm_dependencies/
          key: dependencies-${{ github.ref }}
        
