name: OpenFPM_CI

on:
  pull_request:
  push:
    branches:
      - master
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: yum install -y openssh-clients cmake wget git gcc-c++ gcc-gfortran python39 bzip2 diffutils zlib-devel
      - name: Print dependencies
        run: mkdir -p openfpm_dependencies
      - name: Build
        run: ls
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: openfpm_dependencies/
          key: dependencies-${{ github.ref }}
        
