name: OpenFPM_CI

on:
  pull_request:
  push:
    branches:
      - master
  release:

jobs:
  build_almalinux:
    runs-on: ubuntu-latest
    container: almalinux:8.5
    steps:
      - name: Install dependencies
        run: |
          yum makecache --refresh
          yum install -y openssh-clients cmake ccache wget git gcc-c++ gcc-gfortran python39 bzip2 diffutils zlib-devel
          ln -s /usr/bin/python3 /usr/bin/python
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: Restore Cache dependencies
        uses: actions/cache/restore@v3
        with:
          path: ~/openfpm_dependencies/
          key: dependencies-${{ github.ref }}
      - name: Build
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          ./build.sh $(pwd) unused pdata 0 ${{ github.ref }}
      - uses: actions/cache/save@v3
        if: always()
        with:
          path: ~/openfpm_dependencies/
          key: dependencies-${{ github.ref }}
      - name: Create bundle
        run: |
          ln -s ./LICENSE.md bsd3.txt
          ln -s ./README.md README.txt
          cd build
          source $HOME/openfpm_vars
          export DEP_PACKING=~/openfpm_dependencies/ ;
          printf " -DCPACK_RUN_INSTALL_DEPENDENCIES=ON" >> cmake_build_options;
          cp $HOME/openfpm_vars $HOME/openfpm_dependencies/
          cp $HOME/.openfpm.mk $HOME/openfpm_dependencies/
          bash cmake_build_options;
          echo "Calling CPACK"
          cpack
          
          if [ $? -ne 0 ]; then
            echo "Error creating package"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: openfpm_almalinux
          path: ./openfpm_pdata-$ofp_version-Almalinux.pkg

  build_macos:
    runs-on: macos-latest
    steps:
      - name: Setup GNU Fortran
        uses: modflowpy/install-gfortran-action@v1
      - name: Install dependencies
        run: |
          brew install cmake wget gcc gnu-sed
          export CC=gcc-12
          export CXX=g++-12
          alias gcc=gcc-12
          alias g++=g++-12
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: Restore Cache dependencies
        uses: actions/cache/restore@v3
        with:
          path: ~/openfpm_dependencies/
          key: dependencies-${{ github.ref }}
      - name: Build
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          ./build.sh $(pwd) unused pdata 0 ${{ github.ref }}
      - uses: actions/cache/save@v3
        if: always()
        with:
          path: ~/openfpm_dependencies/
          key: dependencies-${{ github.ref }}

      - name: Create bundle
        run: |
          export PATH="$PATH:/usr/local/bin:"
          source $HOME/openfpm_vars
          version=$(uname -m)
          ln -s ./LICENSE.md bsd3.txt
          ln -s ./README.md README.txt
          cd build
          export DEP_PACKING=/Users/runners/openfpm_dependencies/
          printf " -DCPACK_RUN_INSTALL_DEPENDENCIES=ON" >> cmake_build_options;
          cp $HOME/openfpm_vars $HOME/openfpm_dependencies/
          cp $HOME/.openfpm.mk $HOME/openfpm_dependencies/
          bash cmake_build_options;
          echo "Calling CPACK"
          cpack -G productbuild osx
          if [ $? -ne 0 ]; then
            echo "Error creating package"
            exit 1
          fi
          mv openfpm_pdata-$ofp_version-Darwin.pkg openfpm-$ofp_version-Darwin-$version.pkg

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: openfpm_macos
          path: ./openfpm-$ofp_version-Darwin-$version.pkg
