name: OpenFPM_CI

on:
  pull_request:
  push:
    branches:
      - master
  release:

jobs:
  build_almalinux:
    runs-on: ubuntu-latest
    container: almalinux:8.5
    steps:
      - name: Install dependencies
        run: |
          yum install -y openssh-clients cmake wget git gcc-c++ gcc-gfortran python39 bzip2 diffutils zlib-devel rpm-build
          ln -s /usr/bin/python3 /usr/bin/python
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Restore Cache dependencies
        uses: actions/cache/restore@v3
        with:
          path: ~/openfpm_dependencies/
          key: dependencies-${{ github.ref }}
      - name: Setup Ccache
        run: |
          wget https://github.com/ccache/ccache/releases/download/v4.8/ccache-4.8-linux-x86_64.tar.xz
          tar -xvf ccache-4.8-linux-x86_64.tar.xz -C ~
          export PATH="~/ccache-4.8-linux-x86_64/ccache:$PATH"
          mkdir -p ~/openfpm_dependencies/ccache
          export CCACHE_DIR="$HOME/openfpm_dependencies/ccache"
      - name: Build
        run: |
          export PATH="~/openfpm_dependencies/ccache-4.8-linux-x86_64/ccache:$PATH"
          ./build.sh $(pwd) unused pdata 0 ${{ github.ref }}
      - uses: actions/cache/save@v3
        if: always()
        with:
          path: ~/openfpm_dependencies/
          key: dependencies-${{ github.ref }}
      - name: Create bundle
        run: |
          export PATH="$PATH:/usr/local/bin:"
          source $HOME/openfpm_vars
          version=$(uname -m)
          ln -s ./LICENSE.md bsd3.txt
          ln -s ./README.md README.txt
          cd build
          export DEP_PACKING=~/openfpm_dependencies/${{ github.ref }}/
          printf " -DCPACK_RUN_INSTALL_DEPENDENCIES=ON" >> cmake_build_options;
          bash cmake_build_options;
          cp ~/openfpm_vars ~/openfpm_dependencies/${{ github.ref }}/
          cp ~/.openfpm.mk ~/openfpm_dependencies/${{ github.ref }}/
          echo "Calling CPACK"
          cpack -G tgz centos
          if [ $? -ne 0 ]; then
            echo "Error creating package"
            exit 1
          fi
          mv openfpm_pdata-$ofp_version-Linux.rpm openfpm-$ofp_version-nightly-Linux-$version.rpm

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: openfpm_macos
          path: openfpm-$ofp_version-nightly--Linux-$version.rpm

  build_macos:
    runs-on: macos-latest
    steps:
      - name: Setup GNU Fortran
        uses: modflowpy/install-gfortran-action@v1
      - name: Install dependencies
        run: |
          brew install cmake wget gcc gnu-sed
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      #- name: Restore Cache dependencies
      #  uses: actions/cache/restore@v3
      #  with:
      #    path: ~/openfpm_dependencies/
      #    key: dependencies-${{ github.ref }}
      - name: Build
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          ./build.sh $(pwd) unused pdata 0 ${{ github.ref }}
      - uses: actions/cache/save@v3
        if: always()
        with:
          path: ~/openfpm_dependencies/
          key: dependencies-${{ github.ref }}

      - name: Create bundle
        run: |
          export PATH="$PATH:/usr/local/bin:"
          source $HOME/openfpm_vars
          version=$(uname -m)
          ln -s ./LICENSE.md bsd3.txt
          ln -s ./README.md README.txt
          cd build
          export DEP_PACKING=~/openfpm_dependencies/${{ github.ref }}/
          printf " -DCPACK_RUN_INSTALL_DEPENDENCIES=ON" >> cmake_build_options;
          bash cmake_build_options;
          cp ~/openfpm_vars ~/openfpm_dependencies/${{ github.ref }}/
          cp ~/.openfpm.mk ~/openfpm_dependencies/${{ github.ref }}/
          echo "Calling CPACK"
          cpack -G productbuild osx
          if [ $? -ne 0 ]; then
            echo "Error creating package"
            exit 1
          fi
          mv openfpm_pdata-$ofp_version-Darwin.pkg openfpm-$ofp_version-nightly-Darwin-$version.pkg

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: openfpm_macos
          path: ./openfpm-$ofp_version-nightly-Darwin-$version.pkg
