name: OpenFPM_CI

on:
  pull_request:
  push:
    branches:
      - master
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    container: almalinux:8.5
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yum install -y openssh-clients cmake wget git gcc-c++ gcc-gfortran python39 bzip2 diffutils zlib-devel
      - name: make dependencies folder
        run: mkdir -p openfpm_dependencies
      - name: LS
        run: ls
      - name: Build
        run: ./build.sh $(pwd) unused pdata 0 ${{ github.ref }}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: openfpm_dependencies/
          key: dependencies-${{ github.ref }}
        
