name: OpenFPM_CI

on:
  pull_request:
  push:
    branches:
      - master
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install -y openssh-client cmake wget git g++ gfortran python-is-python3 bzip2 diffutils zlib1g-dev
      - name: make dependencies folder
        run: mkdir -p openfpm_dependencies
      - name: LS
        run: ls
      - name: Build
        run: ./build.sh $(pwd) unused pdata 0 ${{ github.ref }}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: openfpm_dependencies/
          key: dependencies-${{ github.ref }}
        
